export { default as Login } from "./Login"
export { default as Logout } from "./Logout"
export { default as Register } from "./Register"
export { default as NotFound} from "./NotFound"

// Admin pages
export { default as SellerDashboard } from "./SellerDashboard"
export { default as Category } from "./Admin/Category"
export { default as Orders } from "./Admin/Orders"
export { default as AdminProducts } from "./Admin/AdminProducts"
export { default as StockManagement } from "./Admin/StockManagement"
export { default as AddProducts } from "./Admin/AddProducts"
export { default as UpdateProducts } from "./Admin/UpdateProducts"
export { default as Shop } from "./Admin/Shop"
export { default as Forecast } from "./Admin/Forecast"
export { default as Report } from "./Admin/Report"

//Buyer Pages
export { default as Home} from "./Buyer/home"
export { default as ProductPage } from "./Buyer/productpage" 
export { default as Products } from "./Buyer/products"
export { default as Cart } from "./Buyer/cart"
export { default as ShopPage} from "./Buyer/shoppage"
export { default as Checkout} from "./Buyer/checkout"
export { default as MyPurchase} from "./Buyer/mypurchase"
export { default as MyAccount} from "./Buyer/myaccount"